### ISSUE TITLE
Layout of navigation menu is broken at mobile viewport sizes

### ISSUE THREAD

**Issue by GrantASL19** [ASL-19/civicdr#28] opened 2017-07-18 20:47 UTC
The navigation menu layout that kicks in a viewport widths of 990px and below is broken:

![civicdr-menu-mobile-chrome-60](https://user-images.githubusercontent.com/30265160/28338886-46cdb22a-6bd8-11e7-969c-9d195c88a51d.png)

It looks like #nav-block-browse isn’t entirely moved into the viewport – it ends up with a right value of -2rem. The layout of the icon and links also doesn’t look finished.

**Comment by tiffrobo** [comment] 2018-04-09 15:57
Is this a duplicate of #33 ?

**Comment by GrantASL19** [comment] 2018-04-09 17:35
@tiffrobo It’s a different issue. This one is a responsive layout bug; #33 is a UI state management/behaviour bug.

(Not sure if either is still a problem at this point – it’s been a while since I reported them!)

**Comment by tiffrobo** [comment] 2018-04-09 21:54
Ok thanks! I will create a 'Test again' sprint and most likely all the bugs will go there ;)

**Closed as completed** 2018-05-16 19:21 UTC
Labels: bug, mobile
